#!/usr/bin/env bash
#
# Author: Archer Reilly
# Date: 26/Mar/2016
# File: TrainTest
# Desc: glue script that prepare train and test data, train and test
#       and give out accuracy
#
# Produced By CSRGXTU
./PrepareTrainingData.py $1

./PrepareTestingData.py $1

../bin/bin/crf_learn template-file ../data/TeamRank/$1.train.csv model-file

../bin/bin/crf_test -m model-file ../data/TeamRank/$1.test.csv > result.log

./CRFAccurate.py result.log
